services:
  ros2_simulation:
    build: .
    image: hospital_robot_sim:latest
    container_name: ros2_hospital_container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - .:/ros2_ws/src/hospital_robot_project
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
